CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE,
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'deactivated', 'purged', 'suspended')),
    deactivated_at TIMESTAMPTZ NULL,
    deleted_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users__status ON users(status);
CREATE INDEX IF NOT EXISTS idx_users__deactivated_at ON users(deactivated_at);
CREATE INDEX IF NOT EXISTS idx_users__auth_user_id ON users(auth_user_id);

CREATE TABLE IF NOT EXISTS map_templates (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    map_type TEXT NOT NULL CHECK (map_type IN ('field', 'village', 'dungeon')),
    required_level INT NOT NULL DEFAULT 1 CHECK (required_level >= 1),
    spawn_x INT NOT NULL DEFAULT 0,
    spawn_y INT NOT NULL DEFAULT 0,
    spawn_z INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS monster_templates (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    level INT NOT NULL DEFAULT 1 CHECK (level >= 1),
    max_hp INT NOT NULL CHECK (max_hp > 0),
    attack_power INT NOT NULL DEFAULT 0,
    defense_power INT NOT NULL DEFAULT 0,
    experience_reward INT NOT NULL DEFAULT 0 CHECK (experience_reward >= 0),
    gold_min INT NOT NULL DEFAULT 0 CHECK (gold_min >= 0),
    gold_max INT NOT NULL DEFAULT 0 CHECK (gold_max >= gold_min),
    respawn_seconds INT NOT NULL DEFAULT 30 CHECK (respawn_seconds >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS item_templates (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    item_type TEXT NOT NULL CHECK (item_type IN ('weapon', 'armor', 'consumable', 'scroll', 'misc')),
    required_level INT NOT NULL DEFAULT 1 CHECK (required_level >= 1),
    required_class TEXT NULL CHECK (required_class IS NULL OR required_class IN ('warrior', 'mage', 'archer', 'all')),
    attack_bonus INT NOT NULL DEFAULT 0,
    defense_bonus INT NOT NULL DEFAULT 0,
    buy_price INT NOT NULL DEFAULT 0 CHECK (buy_price >= 0),
    sell_price INT NOT NULL DEFAULT 0 CHECK (sell_price >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS skill_templates (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    character_class TEXT NOT NULL CHECK (character_class IN ('warrior', 'mage', 'archer')),
    required_level INT NOT NULL DEFAULT 1 CHECK (required_level >= 1),
    max_level INT NOT NULL DEFAULT 10 CHECK (max_level >= 1),
    mp_cost INT NOT NULL DEFAULT 0 CHECK (mp_cost >= 0),
    cooldown_seconds INT NOT NULL DEFAULT 0 CHECK (cooldown_seconds >= 0),
    range_distance INT NOT NULL DEFAULT 1 CHECK (range_distance >= 0),
    damage_multiplier DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS quest_templates (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    quest_type TEXT NOT NULL CHECK (quest_type IN ('story', 'repeatable')),
    required_level INT NOT NULL DEFAULT 1 CHECK (required_level >= 1),
    target_monster_id INT NULL REFERENCES monster_templates(id) ON DELETE SET NULL,
    target_count INT NOT NULL DEFAULT 1 CHECK (target_count >= 1),
    reward_xp INT NOT NULL DEFAULT 0 CHECK (reward_xp >= 0),
    reward_gold INT NOT NULL DEFAULT 0 CHECK (reward_gold >= 0),
    reward_item_id INT NULL REFERENCES item_templates(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_quest_templates__target_monster_id ON quest_templates(target_monster_id);
CREATE INDEX IF NOT EXISTS idx_quest_templates__reward_item_id ON quest_templates(reward_item_id);

CREATE TABLE IF NOT EXISTS monster_drop_templates (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monster_template_id INT NOT NULL REFERENCES monster_templates(id) ON DELETE CASCADE,
    item_template_id INT NOT NULL REFERENCES item_templates(id) ON DELETE CASCADE,
    drop_rate DOUBLE PRECISION NOT NULL CHECK (drop_rate >= 0.0001 AND drop_rate <= 1.0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_monster_drop_templates__monster_template_id ON monster_drop_templates(monster_template_id);
CREATE INDEX IF NOT EXISTS idx_monster_drop_templates__item_template_id ON monster_drop_templates(item_template_id);

CREATE TABLE IF NOT EXISTS map_monster_spawns (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_template_id INT NOT NULL REFERENCES map_templates(id) ON DELETE CASCADE,
    monster_template_id INT NOT NULL REFERENCES monster_templates(id) ON DELETE CASCADE,
    max_count INT NOT NULL DEFAULT 1 CHECK (max_count >= 1),
    min_x INT NOT NULL DEFAULT 0,
    max_x INT NOT NULL DEFAULT 0,
    min_y INT NOT NULL DEFAULT 0,
    max_y INT NOT NULL DEFAULT 0,
    min_z INT NOT NULL DEFAULT 0,
    max_z INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_map_monster_spawns__coords CHECK (max_x >= min_x AND max_y >= min_y AND max_z >= min_z)
);

CREATE INDEX IF NOT EXISTS idx_map_monster_spawns__map_template_id ON map_monster_spawns(map_template_id);
CREATE INDEX IF NOT EXISTS idx_map_monster_spawns__monster_template_id ON map_monster_spawns(monster_template_id);

CREATE TABLE IF NOT EXISTS monster_instances (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_template_id INT NOT NULL REFERENCES map_templates(id) ON DELETE CASCADE,
    monster_template_id INT NOT NULL REFERENCES monster_templates(id) ON DELETE CASCADE,
    spawn_id INT NOT NULL REFERENCES map_monster_spawns(id) ON DELETE CASCADE,
    instance_id INT NULL,
    status TEXT NOT NULL DEFAULT 'alive' CHECK (status IN ('alive', 'defeated')),
    current_hp INT NOT NULL CHECK (current_hp >= 0),
    position_x INT NOT NULL DEFAULT 0,
    position_y INT NOT NULL DEFAULT 0,
    position_z INT NOT NULL DEFAULT 0,
    defeated_at TIMESTAMPTZ NULL,
    respawn_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_monster_instances__map_template_id_status ON monster_instances(map_template_id, status);
CREATE INDEX IF NOT EXISTS idx_monster_instances__status_respawn_at ON monster_instances(status, respawn_at);
CREATE INDEX IF NOT EXISTS idx_monster_instances__monster_template_id ON monster_instances(monster_template_id);
CREATE INDEX IF NOT EXISTS idx_monster_instances__spawn_id ON monster_instances(spawn_id);
CREATE INDEX IF NOT EXISTS idx_monster_instances__instance_id ON monster_instances(instance_id);

CREATE TABLE IF NOT EXISTS characters (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL UNIQUE,
    character_class TEXT NOT NULL CHECK (character_class IN ('warrior', 'mage', 'archer')),
    level INT NOT NULL DEFAULT 1 CHECK (level >= 1),
    experience INT NOT NULL DEFAULT 0 CHECK (experience >= 0),
    current_hp INT NOT NULL CHECK (current_hp >= 0),
    max_hp INT NOT NULL CHECK (max_hp > 0),
    current_mp INT NOT NULL CHECK (current_mp >= 0),
    max_mp INT NOT NULL CHECK (max_mp > 0),
    attack_power INT NOT NULL DEFAULT 10,
    defense_power INT NOT NULL DEFAULT 5,
    gold INT NOT NULL DEFAULT 100 CHECK (gold >= 0),
    warehouse_gold INT NOT NULL DEFAULT 0 CHECK (warehouse_gold >= 0),
    skill_points INT NOT NULL DEFAULT 0 CHECK (skill_points >= 0),
    current_map_id INT NOT NULL REFERENCES map_templates(id) ON DELETE RESTRICT,
    position_x INT NOT NULL DEFAULT 0,
    position_y INT NOT NULL DEFAULT 0,
    position_z INT NOT NULL DEFAULT 0,
    equipped_items JSONB NULL DEFAULT '[]',
    deleted_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_characters__user_id ON characters(user_id);
CREATE INDEX IF NOT EXISTS idx_characters__current_map_id ON characters(current_map_id);
CREATE INDEX IF NOT EXISTS idx_characters__deleted_at ON characters(deleted_at);

CREATE TABLE IF NOT EXISTS character_skills (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id INT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    skill_template_id INT NOT NULL REFERENCES skill_templates(id) ON DELETE CASCADE,
    skill_level INT NOT NULL DEFAULT 1 CHECK (skill_level >= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_character_skills__char_skill UNIQUE (character_id, skill_template_id)
);

CREATE INDEX IF NOT EXISTS idx_character_skills__character_id ON character_skills(character_id);
CREATE INDEX IF NOT EXISTS idx_character_skills__skill_template_id ON character_skills(skill_template_id);

CREATE TABLE IF NOT EXISTS character_inventory (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id INT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    item_template_id INT NOT NULL REFERENCES item_templates(id) ON DELETE CASCADE,
    storage_type TEXT NOT NULL DEFAULT 'inventory' CHECK (storage_type IN ('inventory', 'warehouse')),
    slot_index INT NOT NULL CHECK (slot_index >= 0),
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity >= 1),
    enchant_level INT NOT NULL DEFAULT 0 CHECK (enchant_level >= 0),
    is_equipped BOOLEAN NOT NULL DEFAULT FALSE,
    equipped_slot TEXT NULL CHECK (equipped_slot IS NULL OR equipped_slot IN ('weapon', 'shield', 'helmet', 'body_armor', 'boots', 'ring', 'necklace')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_character_inventory__char_storage_slot ON character_inventory(character_id, storage_type, slot_index);
CREATE INDEX IF NOT EXISTS idx_character_inventory__item_template_id ON character_inventory(item_template_id);

CREATE TABLE IF NOT EXISTS character_quests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id INT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    quest_template_id INT NOT NULL REFERENCES quest_templates(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'in_progress' CHECK (status IN ('in_progress', 'completed', 'abandoned')),
    progress_count INT NOT NULL DEFAULT 0 CHECK (progress_count >= 0),
    completed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_character_quests__character_id ON character_quests(character_id);
CREATE INDEX IF NOT EXISTS idx_character_quests__quest_template_id ON character_quests(quest_template_id);
CREATE INDEX IF NOT EXISTS idx_character_quests__char_quest ON character_quests(character_id, quest_template_id);

CREATE TABLE IF NOT EXISTS announcements (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('notice', 'patch', 'event')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_announcements__category_published ON announcements(category, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_announcements__is_active_published ON announcements(is_active, published_at DESC);

CREATE TABLE IF NOT EXISTS scheduler_jobs (
    job_slug text PRIMARY KEY,
    last_ran_at timestamptz,
    state jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- Seed one starter field map so character creation always has a valid
-- current_map_id to reference (this is the exact gap we suspect broke the
-- BackendX-hosted backend).
INSERT INTO map_templates (name, map_type, required_level, spawn_x, spawn_y, spawn_z)
VALUES ('Starter Field', 'field', 1, 0, 0, 0);
